// Generated by CoffeeScript 1.9.3
(function() {
  window.RACENIGHT = window.RACENIGHT || {};

  $(document).on("click", ".renamer-field", function() {
    var domainClass, element, id, newValue;
    console.log(this.innerHTML);
    newValue = prompt("Rename field", this.innerHTML);
    domainClass = $(this).attr("data-class");
    id = $(this).attr("data-id");
    console.log(domainClass);
    console.log(newValue);
    console.log(id);
    element = this;
    if (newValue) {
      return $.ajax({
        url: "/ajaxRenaming/index?dateTAG=" + new Date().getTime(),
        data: {
          newValue: newValue,
          domainClass: domainClass,
          id: id
        },
        error: function(jqXHR, textStatus, errorThrown) {
          return console.log('ajax error');
        },
        success: function(data) {
          if (data.newValue) {
            console.log("here newValue = " + data.newValue);
            return element.innerHTML = data.newValue;
          } else {
            return console.log("error");
          }
        }
      });
    }
  });

}).call(this);
